version: '3.0'

services:
  neo4j:
    build: .
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-runtime/data:/data
      - ./neo4j-runtime/logs:/logs
      - ./neo4j-runtime/import:/var/lib/neo4j/import
      - ./neo4j-runtime/plugins:/plugins
      - ./cyphers:/cyphers